
cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

secretsibmcloud:
  enabled: false
  imagePullSecrets: image-pull-secret-ibm-cloud

service:
  name: {{ .ServiceName }}
  type: LoadBalancer
  externalPort: 8000
  containerPort: 8000
  nodePort: 31070
  replicaCount: 1

  GITACCOUNT:
  APITOKEN:
  GITREPO: "github.com/OlegGorJ/config-data.git"

  CONFIGFILE: services
  Release: "1.0"
  Environment: sandbox
  K8s_namespace: default
  APIVER: v1
  #NodeSelector: services

image:
  repository: "oleggorj/service-config-data:1.0"
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 100Mi
