apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: service-config-data
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/advancedanalyticscanada/service-config-data:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/advancedanalyticscanada/service-config-data:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: service-config-data
        chartPath: charts/service-config-data
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/advancedanalyticscanada/service-config-data'
          image.tag: '{{.DIGEST_HEX}}'
